Web/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.DAO;
using Model.PN;
using PagedList;

namespace Web.Controllers
{
    public class ClientesController : Controller
    {
        private Entities db = new Entities();

        //GET: Buscando clientes por nome
        public ActionResult BuscarClientes(string textoBuscado)
        {

       
            //Verifica se um texto foi buscado
            if (!String.IsNullOrEmpty(textoBuscado))
            {
                return View(pnClientes.RetornaClientesPorNome(textoBuscado));
            }
            
            //Se não retorna todos os clientes
            return View(pnClientes.RetornaClientes());

        }

        //Clientes e busca
        public ActionResult Index(int? page, string textoBuscado, string metodo)
        {
            int pageSize = 5;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            IPagedList<Cliente> clientes;
            
            //Verifica se um texto foi buscado
            if (!String.IsNullOrEmpty(textoBuscado))
            {
                if (!String.IsNullOrEmpty(metodo))
                {
                    clientes = pnClientes.RetornaClientesPorInicial(textoBuscado).ToPagedList(pageIndex, pageSize);
                    return View(clientes);
                }
                else {
                    clientes = pnClientes.RetornaClientesPorNome(textoBuscado).ToPagedList(pageIndex, pageSize);
                    return View(clientes);
                }
                
            }

            clientes = pnClientes.RetornaClientesPorNome("").ToPagedList(pageIndex, pageSize);
            return View(clientes);

        }

        // GET: Clientes/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Clientes.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // GET: Clientes/Create
        public ActionResult Create()
        {
            ViewBag.ClienteID = new SelectList(db.Enderecos, "ClienteID", "Rua");
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClienteID,Nome")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                cliente.ClienteID = Guid.NewGuid();
                db.Clientes.Add(cliente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClienteID = new SelectList(db.Enderecos, "ClienteID", "Rua", cliente.ClienteID);
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Clientes.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClienteID = new SelectList(db.Enderecos, "ClienteID", "Rua", cliente.ClienteID);
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClienteID,Nome")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cliente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClienteID = new SelectList(db.Enderecos, "ClienteID", "Rua", cliente.ClienteID);
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Clientes.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Cliente cliente = db.Clientes.Find(id);
            db.Clientes.Remove(cliente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.DAO;
using Model.PN;
using PagedList;

namespace Web.Controllers
{
    public class PedidosController : Controller
    {
        private Entities db = new Entities();

        /*
        // GET: Pedidos
        public ActionResult Index()
        {
            var pedidos = db.Pedidos.Include(p => p.Cliente).Include(p => p.DetalhesPedido);
            return View(pedidos.ToList());
        }
        */

        //Clientes e busca
        public ActionResult Index(int? page, Guid? clienteID, int? mes, int? ano)
        {
            ViewBag.ClienteId = clienteID.ToString();
            
            int pageSize = 5;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

            IPagedList<Pedido> pedidos;
            
            //Verifica se um cliente foi buscado
            if (clienteID.HasValue)
            {
                pedidos = pnPedidos.RetornaPedidosDoCliente(clienteID.Value).ToPagedList(pageIndex, pageSize);

                //Se algum ano foi escolhido
                if (ano > 0)
                {

                    //Se escolheu ano e mês
                    if (mes > 0)
                    {
                        pedidos = pedidos.Where(x => x.Data.Month == mes && x.Data.Year == ano).ToList().ToPagedList(pageIndex, pageSize);

                    }//Se escolheu apenas ano
                    else
                    {
                        pedidos = pedidos.Where(x => x.Data.Year == ano).ToList().ToPagedList(pageIndex, pageSize);

                    }
                    
                }

                ViewBag.Total = pnPedidos.RetornaValorTotalDeListaDePedido(pedidos.ToList());

                return View(pedidos);
            }

            pedidos = pnPedidos.RetornaPedidos().ToPagedList(pageIndex, pageSize);
            return View(pedidos);

        }
        
        /* GET: Pedidos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = db.Pedidos.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            return View(pedido);
        }*/

        // GET: Pedidos/Create
        public ActionResult Create()
        {
            ViewBag.ClienteID = new SelectList(db.Clientes, "ClienteID", "Nome");
            ViewBag.NroPedido = new SelectList(db.DetalhesPedido, "NroPedido", "NroPedido");
            return View();
        }

        // POST: Pedidos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClienteID,NroPedido,Data")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                db.Pedidos.Add(pedido);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClienteID = new SelectList(db.Clientes, "ClienteID", "Nome", pedido.ClienteID);
            ViewBag.NroPedido = new SelectList(db.DetalhesPedido, "NroPedido", "NroPedido", pedido.NroPedido);
            return View(pedido);
        }

        // GET: Pedidos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = db.Pedidos.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClienteID = new SelectList(db.Clientes, "ClienteID", "Nome", pedido.ClienteID);
            ViewBag.NroPedido = new SelectList(db.DetalhesPedido, "NroPedido", "NroPedido", pedido.NroPedido);
            return View(pedido);
        }

        // POST: Pedidos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClienteID,NroPedido,Data")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pedido).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClienteID = new SelectList(db.Clientes, "ClienteID", "Nome", pedido.ClienteID);
            ViewBag.NroPedido = new SelectList(db.DetalhesPedido, "NroPedido", "NroPedido", pedido.NroPedido);
            return View(pedido);
        }

        // GET: Pedidos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = db.Pedidos.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            return View(pedido);
        }

        // POST: Pedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pedido pedido = db.Pedidos.Find(id);
            db.Pedidos.Remove(pedido);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web/Views/Clientes/BuscarClientes.cshtml
@model IEnumerable<Model.DAO.Cliente>

@{
    ViewBag.Title = "BuscarClientes";
}

<h2>Buscar Clientes</h2>


@using (Html.BeginForm("BuscarClientes", "Clientes", FormMethod.Get))
{
    <p>
        Nome do Cliente: @Html.TextBox("textoBuscado")
        <input class="btn-primary" type="submit" value="Buscar" />
    </p>
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Endereco.Rua)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Endereco.Rua)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ClienteID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ClienteID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ClienteID })
            </td>
        </tr>
    }

</table>

Web/Views/Clientes/Create.cshtml
@model Model.DAO.Cliente

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/Clientes/Delete.cshtml
@model Model.DAO.Cliente

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco.Rua)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.Rua)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Web/Views/Clientes/Details.cshtml
@model Model.DAO.Cliente

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco.Rua)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.Rua)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ClienteID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Web/Views/Clientes/Edit.cshtml
@model Model.DAO.Cliente

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ClienteID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/Clientes/Index.cshtml
@model PagedList.IPagedList<Model.DAO.Cliente>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>

@using (Html.BeginForm("Index", "Clientes", FormMethod.Get))
{
    <p>
        Nome do Cliente: @Html.TextBox("textoBuscado")
        <input class="btn-primary" type="submit" value="Buscar" />
    </p>

    <p>
        @Html.ActionLink("A", "Index", new { textoBuscado = "A", metodo = "inicial" })
        @Html.ActionLink("B", "Index", new { textoBuscado = "B", metodo = "inicial" })
        @Html.ActionLink("C", "Index", new { textoBuscado = "C", metodo = "inicial" })
        @Html.ActionLink("D", "Index", new { textoBuscado = "D", metodo = "inicial" })
        @Html.ActionLink("E", "Index", new { textoBuscado = "E", metodo = "inicial" })
        @Html.ActionLink("F", "Index", new { textoBuscado = "F", metodo = "inicial" })
        @Html.ActionLink("G", "Index", new { textoBuscado = "G", metodo = "inicial" })
        @Html.ActionLink("H", "Index", new { textoBuscado = "H", metodo = "inicial" })
        @Html.ActionLink("I", "Index", new { textoBuscado = "I", metodo = "inicial" })
        @Html.ActionLink("J", "Index", new { textoBuscado = "J", metodo = "inicial" })
        @Html.ActionLink("K", "Index", new { textoBuscado = "K", metodo = "inicial" })
        @Html.ActionLink("L", "Index", new { textoBuscado = "L", metodo = "inicial" })
        @Html.ActionLink("M", "Index", new { textoBuscado = "M", metodo = "inicial" })
        @Html.ActionLink("N", "Index", new { textoBuscado = "N", metodo = "inicial" })
        @Html.ActionLink("O", "Index", new { textoBuscado = "O", metodo = "inicial" })
        @Html.ActionLink("P", "Index", new { textoBuscado = "P", metodo = "inicial" })
        @Html.ActionLink("Q", "Index", new { textoBuscado = "Q", metodo = "inicial" })
        @Html.ActionLink("R", "Index", new { textoBuscado = "R", metodo = "inicial" })
        @Html.ActionLink("S", "Index", new { textoBuscado = "S", metodo = "inicial" })
        @Html.ActionLink("T", "Index", new { textoBuscado = "T", metodo = "inicial" })
        @Html.ActionLink("U", "Index", new { textoBuscado = "U", metodo = "inicial" })
        @Html.ActionLink("V", "Index", new { textoBuscado = "V", metodo = "inicial" })
        @Html.ActionLink("W", "Index", new { textoBuscado = "W", metodo = "inicial" })
        @Html.ActionLink("X", "Index", new { textoBuscado = "X", metodo = "inicial" })
        @Html.ActionLink("Y", "Index", new { textoBuscado = "Y", metodo = "inicial" })
        @Html.ActionLink("Z", "Index", new { textoBuscado = "Z", metodo = "inicial" })
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model[0].Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Endereco.Rua)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Endereco.Rua)
            </td>
            <td>
                <a href="@Url.Action("Index", "Pedidos", new { clienteID = item.ClienteID })" class="btn btn-primary">Pedidos &nbsp;<span class="glyphicon glyphicon-gift"></span></a>|
                @Html.ActionLink("Edit", "Edit", new { id = item.ClienteID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ClienteID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ClienteID })
            </td>
        </tr>
    }
</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))